### ISSUE TITLE
اضافه کردن پی دی اف

### ISSUE THREAD

**Issue by mohsensaremi** [Behnamhb/learning-docker-fanap#1]
لطفا پی دی اف آموزش هارو هم اضافه کنید.
فونت ها بهم ریخته نشون داده می شه تو فایل وورد.

**Comment by sabramooz** [comment]
توصیه من استفاده از markdown هست

**Comment by Behnamhb** [comment]
سلام
چون با فونت irlotus  سند رو نوشتم باید فونت رو نصب کنی تا بتونی از اون
استفاده کنی

‫‪pooya‬‏ <‪notifications@github.com‬‏> در تاریخ دوشنبه ۱۲ اکتبر ۲۰۲۰ ساعت
۱۰:۴۶ نوشت:‬

**Comment by Behnamhb** [comment]
این هم فایل pdf

‫‪behnam hasanbeygi‬‏ <‪behnam.hasanbeygi@gmail.com‬‏> در تاریخ دوشنبه ۱۲
اکتبر ۲۰۲۰ ساعت ۲۱:۵۰ نوشت:‬
